version: '3.8'

services:
  backpilot-frontend:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: backpilot-app
    
  # Development service (optional)
  backpilot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev